openapi: 3.0.1
info:
  title: E-diaristas
  description: Api Backend da Aplicação E-diarista.
  version: 1.0.0
  contact:
    name: Vitoria
    url: https://www.github.com/vitoriapac
    email: vitoriac.pac@gmail.com
servers:
  - url: http://localhost:3001
    description: Aplicação Nest Local
tags:
  -name: Api
  -name: Diaristas
  -name: Endereco
paths:
  /api:
    get:
      operationId: getLinks
      tags:
        - Api
      description: Exibi os links iniciais da API
        - name: cep
          in: query
          required: true
          schema:
            type: string
          example: '04614903'
      responses:
        '200':
          description: Exibição foi realizada com sucesso
          content:
            'aplication/json':
              schema:
                type: object
                properties:
                  links:
                    type: array
                    items:
                      $ref: '#/components/schemas/LinkResponse'
  /api/diaristas/localidades:
    get:
      operationId: getDiaristasLocalidades
      tags:
        - Diaristas
      description: Buscar diaristas que atendem uma determinada localidade
      parameters:
        - name: cep
          in: query
          required: true
          schema:
            type: string
          example: '04614903'
      responses:
        '200':
          description: Busca foi realizada com sucesso
          content:
            'aplication/json':
              schema:
                $ref: '#/components/schemas/DiaristaLocalidadePagedResponse'
        '400':
          description: CEP não informado ou inválido
          content:
            'aplication/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: CEP informado não encontrado
          content:
            'aplication/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/diaristas/disponibilidade:
    get:
      operationId: getDisponibilidade
      tags:
        - Diaristas
      description: Verificar a disponibilidade de diaristas por localidade
      parameters:
        - name: cep
          in: query
          required: true
          schema:
            type: string
          example: '04614903'
      responses:
        '200':
          description: Verificação foi realizada com sucesso
          content:
            'aplication/json':
              schema:
                $ref: '#/components/schemas/DisponibilidadeResponse'
        '400':
          description: CEP não informado ou inválido
          content:
            'aplication/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: CEP informado não encontrado
          content:
            'aplication/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/enderecos:
    get:
      operationId: getEndereco
      tags:
        - Endereco
      description: Buscar dados de um endereco por CEP
      parameters:
        - name: cep
          in: query
          required: true
          schema:
            type: string
          example: '04614903'
      responses:
        '200':
          description: Busca foi realizada com sucesso
          content:
            'aplication/json':
              schema:
                $ref: '#/components/schemas/EnderecoResponse'
        '400':
          description: CEP não informado ou inválido
          content:
            'aplication/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: CEP informado não encontrado
          content:
            'aplication/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    DiaristaLocalidadePagedResponse:
      type: object
      properties:
        diaristas:
          type: array
          items:
            $ref: '#/components/schemas/DiaristaLocalidadeResponse'
    DiaristaLocalidadeResponse:
      type: object
      properties:
        nome_completo:
          type: string
        reputacao:
          type: string
          format: double
        foto_usuario:
          type: string
          format: url
        cidade:
          type: string
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
        timestamp:
          type: string
          format: date-time
        message:
          type: string
    EnderecoResponse:
      type: object
      properties:
        cep:
          type: string
        logradouro:
          type: string
        complemento:
          type: string
        bairro:
          type: string
        localidade:
          type: string
        uf:
          type: string
        ibge:
          type: string
    DisponibilidadeResponse:
      type: object
      properties:
        disponibilidade:
          type: boolean
    LinkResponse:
      type: object
      properties:
        type:
          type: string
          enum:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
          rel:
            type: string
          url:
            type: string
            format: url
